arb-dir: lib/app/l10n
template-arb-file: app_cs.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslated.txt

# dart run lean_builder build
# dart run lean_builder watch
